### ISSUE TITLE
Question regarding the test cases

### ISSUE THREAD

**Issue by tariq1890** [procore/manage-version#3]
Hey, thanks for sharing this project on GitHub.

I have a question. I see that you have mocked GitHub API calls. Why not mock the GitHub authenticate call as well? :)

**Comment by ksespinola** [comment]
Great call. I'll open up a PR and link to this issue.

**Comment by ksespinola** [comment]
Resolved here: https://github.com/procore/manage-version/pull/4/files#diff-9bbe76814fb40d228bd77e86772ea0d3

**Comment by ksespinola** [comment]
All done: https://github.com/procore/manage-version/pull/4
